[package]
name = "rust_trajectory_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.3"  # For linear algebra and vectors
rand = "0.8.5"       # For random number generation if needed
